services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
    volumes:
      - tenstar_data:/var/opt/mssql
    networks:
      - app_network

volumes:
  tenstar_data:

networks:
  app_network:
    external: true
